--
-- PostgreSQL database dump
--

\restrict OnA2m80qHwST3ahzjd6Q7R2cQSyh8bmHgnP3dflLs2xabnsV74WjrYpaKpq54jE

-- Dumped from database version 18.1 (Debian 18.1-1.pgdg13+2)
-- Dumped by pg_dump version 18.1 (Debian 18.1-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: assessment_results; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.assessment_results (
    result_id integer NOT NULL,
    comments character varying(255),
    evaluation_date timestamp(6) without time zone,
    score numeric(5,2) NOT NULL,
    assignment_id integer NOT NULL,
    criterion_id integer NOT NULL,
    evaluated_by integer NOT NULL,
    round_id integer NOT NULL
);


ALTER TABLE public.assessment_results OWNER TO postgres;

--
-- Name: assessment_results_result_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.assessment_results ALTER COLUMN result_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessment_results_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assessment_rounds; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.assessment_rounds (
    round_id integer NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    description character varying(255),
    end_date date NOT NULL,
    is_active boolean NOT NULL,
    round_name character varying(100) NOT NULL,
    start_date date NOT NULL,
    phase_id integer NOT NULL,
    is_deleted boolean
);


ALTER TABLE public.assessment_rounds OWNER TO postgres;

--
-- Name: assessment_rounds_round_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.assessment_rounds ALTER COLUMN round_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessment_rounds_round_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evaluation_criteria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.evaluation_criteria (
    criterion_id integer NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    criterion_name character varying(200) NOT NULL,
    description character varying(255),
    max_score numeric(5,2) NOT NULL,
    is_deleted boolean
);


ALTER TABLE public.evaluation_criteria OWNER TO postgres;

--
-- Name: evaluation_criteria_criterion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.evaluation_criteria ALTER COLUMN criterion_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evaluation_criteria_criterion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: internship_assignments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.internship_assignments (
    assignment_id integer NOT NULL,
    assigned_date timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    mentor_id integer NOT NULL,
    phase_id integer NOT NULL,
    student_id integer NOT NULL,
    CONSTRAINT internship_assignments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.internship_assignments OWNER TO postgres;

--
-- Name: internship_assignments_assignment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.internship_assignments ALTER COLUMN assignment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.internship_assignments_assignment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: internship_phases; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.internship_phases (
    phase_id integer NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    description character varying(255),
    end_date date NOT NULL,
    phase_name character varying(100) NOT NULL,
    start_date date NOT NULL,
    is_deleted boolean
);


ALTER TABLE public.internship_phases OWNER TO postgres;

--
-- Name: internship_phases_phase_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.internship_phases ALTER COLUMN phase_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.internship_phases_phase_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mentors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mentors (
    mentor_id integer NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    academic_rank character varying(50),
    department character varying(100)
);


ALTER TABLE public.mentors OWNER TO postgres;

--
-- Name: round_criteria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.round_criteria (
    id integer NOT NULL,
    is_deleted boolean,
    weight numeric(5,2) NOT NULL,
    criterion_id integer NOT NULL,
    round_id integer NOT NULL
);


ALTER TABLE public.round_criteria OWNER TO postgres;

--
-- Name: round_criteria_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.round_criteria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.round_criteria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: students; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.students (
    student_id integer NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    address character varying(255),
    date_of_birth date,
    major character varying(100),
    student_class character varying(50),
    student_code character varying(20) NOT NULL
);


ALTER TABLE public.students OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    email character varying(100) NOT NULL,
    full_name character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    password_hash character varying(255) NOT NULL,
    phone_number character varying(20),
    role character varying(255) NOT NULL,
    username character varying(50) NOT NULL,
    is_deleted boolean,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'MENTOR'::character varying, 'STUDENT'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: assessment_results; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.assessment_results (result_id, comments, evaluation_date, score, assignment_id, criterion_id, evaluated_by, round_id) FROM stdin;
\.


--
-- Data for Name: assessment_rounds; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.assessment_rounds (round_id, created_at, updated_at, description, end_date, is_active, round_name, start_date, phase_id, is_deleted) FROM stdin;
\.


--
-- Data for Name: evaluation_criteria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.evaluation_criteria (criterion_id, created_at, updated_at, criterion_name, description, max_score, is_deleted) FROM stdin;
\.


--
-- Data for Name: internship_assignments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.internship_assignments (assignment_id, assigned_date, status, mentor_id, phase_id, student_id) FROM stdin;
\.


--
-- Data for Name: internship_phases; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.internship_phases (phase_id, created_at, updated_at, description, end_date, phase_name, start_date, is_deleted) FROM stdin;
\.


--
-- Data for Name: mentors; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mentors (mentor_id, created_at, updated_at, academic_rank, department) FROM stdin;
\.


--
-- Data for Name: round_criteria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.round_criteria (id, is_deleted, weight, criterion_id, round_id) FROM stdin;
\.


--
-- Data for Name: students; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.students (student_id, created_at, updated_at, address, date_of_birth, major, student_class, student_code) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, created_at, updated_at, email, full_name, is_active, password_hash, phone_number, role, username, is_deleted) FROM stdin;
\.


--
-- Name: assessment_results_result_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.assessment_results_result_id_seq', 1, false);


--
-- Name: assessment_rounds_round_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.assessment_rounds_round_id_seq', 1, false);


--
-- Name: evaluation_criteria_criterion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.evaluation_criteria_criterion_id_seq', 1, false);


--
-- Name: internship_assignments_assignment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.internship_assignments_assignment_id_seq', 1, false);


--
-- Name: internship_phases_phase_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.internship_phases_phase_id_seq', 1, false);


--
-- Name: round_criteria_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.round_criteria_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- Name: assessment_results assessment_results_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessment_results
    ADD CONSTRAINT assessment_results_pkey PRIMARY KEY (result_id);


--
-- Name: assessment_rounds assessment_rounds_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessment_rounds
    ADD CONSTRAINT assessment_rounds_pkey PRIMARY KEY (round_id);


--
-- Name: evaluation_criteria evaluation_criteria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluation_criteria
    ADD CONSTRAINT evaluation_criteria_pkey PRIMARY KEY (criterion_id);


--
-- Name: internship_assignments internship_assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.internship_assignments
    ADD CONSTRAINT internship_assignments_pkey PRIMARY KEY (assignment_id);


--
-- Name: internship_phases internship_phases_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.internship_phases
    ADD CONSTRAINT internship_phases_pkey PRIMARY KEY (phase_id);


--
-- Name: mentors mentors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mentors
    ADD CONSTRAINT mentors_pkey PRIMARY KEY (mentor_id);


--
-- Name: round_criteria round_criteria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.round_criteria
    ADD CONSTRAINT round_criteria_pkey PRIMARY KEY (id);


--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (student_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: evaluation_criteria ukc3hhcy6lofbmbajghiec16eic; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluation_criteria
    ADD CONSTRAINT ukc3hhcy6lofbmbajghiec16eic UNIQUE (criterion_name);


--
-- Name: students ukcgcf3r5xk73o0etbduc1qxnol; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT ukcgcf3r5xk73o0etbduc1qxnol UNIQUE (student_code);


--
-- Name: internship_phases ukdm4g810jgm2ovbftuh3ggexy; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.internship_phases
    ADD CONSTRAINT ukdm4g810jgm2ovbftuh3ggexy UNIQUE (phase_name);


--
-- Name: round_criteria uke4wj5ai1gl3fp9dyh1hdvwbhi; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.round_criteria
    ADD CONSTRAINT uke4wj5ai1gl3fp9dyh1hdvwbhi UNIQUE (round_id, criterion_id);


--
-- Name: assessment_results ukhu73289qvwduheq2ti2oe74b4; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessment_results
    ADD CONSTRAINT ukhu73289qvwduheq2ti2oe74b4 UNIQUE (assignment_id, round_id, criterion_id);


--
-- Name: internship_assignments ukr0vki3mvi90p02ob771nop5q2; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.internship_assignments
    ADD CONSTRAINT ukr0vki3mvi90p02ob771nop5q2 UNIQUE (student_id, phase_id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: assessment_results fk25cbu4uwejnmmmlpt6872xqo5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessment_results
    ADD CONSTRAINT fk25cbu4uwejnmmmlpt6872xqo5 FOREIGN KEY (assignment_id) REFERENCES public.internship_assignments(assignment_id);


--
-- Name: assessment_results fk4apa29en165etu53qlg0dnr59; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessment_results
    ADD CONSTRAINT fk4apa29en165etu53qlg0dnr59 FOREIGN KEY (criterion_id) REFERENCES public.evaluation_criteria(criterion_id);


--
-- Name: round_criteria fkbe2gcfqnq36obklud6pvv0akj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.round_criteria
    ADD CONSTRAINT fkbe2gcfqnq36obklud6pvv0akj FOREIGN KEY (criterion_id) REFERENCES public.evaluation_criteria(criterion_id);


--
-- Name: assessment_rounds fkcsg58j3jbw51fnber1r0x10i6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessment_rounds
    ADD CONSTRAINT fkcsg58j3jbw51fnber1r0x10i6 FOREIGN KEY (phase_id) REFERENCES public.internship_phases(phase_id);


--
-- Name: assessment_results fkcu1phb5160nbe98t8l9ubspa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessment_results
    ADD CONSTRAINT fkcu1phb5160nbe98t8l9ubspa FOREIGN KEY (evaluated_by) REFERENCES public.users(id);


--
-- Name: internship_assignments fkdcqhohbub55p9h73wcfa0yi7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.internship_assignments
    ADD CONSTRAINT fkdcqhohbub55p9h73wcfa0yi7 FOREIGN KEY (student_id) REFERENCES public.students(student_id);


--
-- Name: assessment_results fkddcvo30cmryijqj1xn1irxc24; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessment_results
    ADD CONSTRAINT fkddcvo30cmryijqj1xn1irxc24 FOREIGN KEY (round_id) REFERENCES public.assessment_rounds(round_id);


--
-- Name: round_criteria fket40xcsika4rvidx27k6ujlu0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.round_criteria
    ADD CONSTRAINT fket40xcsika4rvidx27k6ujlu0 FOREIGN KEY (round_id) REFERENCES public.assessment_rounds(round_id);


--
-- Name: internship_assignments fkf1up5ggjs005kje2qltkqaf82; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.internship_assignments
    ADD CONSTRAINT fkf1up5ggjs005kje2qltkqaf82 FOREIGN KEY (mentor_id) REFERENCES public.mentors(mentor_id);


--
-- Name: mentors fkj4ctbkroopnigg79wj4up8qor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mentors
    ADD CONSTRAINT fkj4ctbkroopnigg79wj4up8qor FOREIGN KEY (mentor_id) REFERENCES public.users(id);


--
-- Name: internship_assignments fkkq2kvkwod6q4vjyb2lmwu9mxv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.internship_assignments
    ADD CONSTRAINT fkkq2kvkwod6q4vjyb2lmwu9mxv FOREIGN KEY (phase_id) REFERENCES public.internship_phases(phase_id);


--
-- Name: students fknl1q3iljhy1184875o5nu9ryy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fknl1q3iljhy1184875o5nu9ryy FOREIGN KEY (student_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict OnA2m80qHwST3ahzjd6Q7R2cQSyh8bmHgnP3dflLs2xabnsV74WjrYpaKpq54jE

